[[section-introduction-and-goals]]
== Introducción y objetivos

=== Visión general
El proyecto consiste en una API REST que proporciona la funcionalidad necesaria para generar preguntas
‘tipo test’, esto es, preguntas con múltiples opciones para elegir como respuesta.
Para realizar la generación de preguntas se utilizará como fuente de información el grafo de conocimiento
de Wikidata.

En este documento se describirá cómo se realiza el proceso para generar las preguntas junto con sus
respuestas, la arquitectura del proyecto software, la descripción de los ‘endpoints’ que expone la
API y, por último, futuros caminos de mejoras para continuar el proyecto.


[[section-state-of-the-art]]
=== Estado del arte

Para la realización del proyecto se ha llevado a cabo un proceso de investigación acerca de cómo se ha abordado
el mismo problema (o similares) en anteriores situaciones. +
A continuación se tratarán varios de los artículos recabados junto con sus ventajas, inconvenientes y similaridades
con nuestro enfoque.


==== Automatic generation of multiple choice questions from slide content using linked data
Tiene como objetivo extraer preguntas a partir de información que localiza en diapositivas. +
Es decir, a partir de un texto localiza entidades y posibles enunciados que utiliza para
la generación de preguntas de múltiple opción.

Permite seleccionar diferentes niveles de dificultad, incluyendo preguntas que son difíciles de responder.
Esto lo consigue utilizando información poco conocida y/o distractores que son semánticamente similares a la
respuesta correcta.

Tiene tres variedades de preguntas:

* _Gap-fill_: se generan a partir de un enunciado en el que una entidad es
mencionada, sustituyendo la entidad por un espacio en blanco y proporcionando
otras entidades similares como distractores.

* _Choose-the-type_: se pregunta por el tipo al que pertenece la entidad.
Los distractores son similares al tipo de la entidad.

* _Jeopardy-style_: son preguntas que incluyen algún tipo de pistas sobre
la respuesta en el enunciado.

Hace uso de DBPedia como fuente de información, y, en cuanto al proceso de verbalizar la información semántica, utiliza un
enfoque muy similar al que hemos adoptado, basado en plantillas o _templates_.
<<slides_2018>>


==== Automatic generation of quizzes from DBpedia according to educational standards
Este artículo busca el desarrollo de un sistema predominantemente enfocado a escuelas.
Utiliza ontologías específicas de este dominio (Eduprogression y
Les Incollables Knowledge base).

Además, al contrario de nuestro proyecto, que solo utiliza una estrategia de generación de preguntas,
este emplea 5 estrategias de generación de preguntas para proporcionar 5 tipos de preguntas diferentes.
<<lyon_2018>>


==== Knowledge questions from knowledge graphs
Utiliza DBPedia como fuente de información.
Hace distincion entre diferentes tipos de predicados y,
al igual que <<slides_2018>> y nuestro propio sistema, utiliza un modelo de plantillas
para verbalizar los enunciados semánticos.

Este proyecto también es capaz de evaluar la dificultad de las preguntas.<<kg_2017>>.


==== Semantic multiple-choice question generation and concept-based assessment
Este sistema destaca en el método que utiliza para variar la dificultad de las preguntas.
Utiliza proximidad entre las entidades en una jerarquía para determinar la dificultad de los
distractores. +
Por ejemplo, para hacer una pregunta más fácil puede elegir entidades que no aparecen
en ninguna relación equivalente (seleccionar una película como distractor de una pregunta
que pregunta por la capital de un país).

Requiere una amplia configuración de diferentes parámetros y no permite eligir la entidad
sobre la que se realizarán las preguntas, tan solo el dominio. +
_No sería posible elegir generar preguntas sobre 'Madrid', sino generar preguntas sobre geografía
en general._

Además, las preguntas generadas son poco comprensibles en lenguaje natural,
siendo del tipo: 'Which one of the following response pairs relate in the
same way as x and y in the relationship p?'
<<semantic_2015>>

=== Linked data

Linked Data son datos estructurados que están interconectados con otros datos.
Linked Data puede expresarse como tripletas semánticas, o simplemente tripletas.
Como su nombre indica, una tripleta es un conjunto de tres entidades que codifica un
enunciado sobre datos semánticos en la forma de una expresión sujeto-predicado objeto
("Bob edad 35", or "Bob conoce_a John”).

// IMAGEN SUBJECT PREDICATE OBJECT
image:triple.svg[alt=Semantic Triple]

Estas conexiones tienen como resultado grafos de información constituidos por las entidades y
las relaciones entre ellas.

// IMAGEN SEVERAL ENTITIES
image:graph.svg[alt=Graph with several entities]

Parte de la visión de Linked Data es convertir a internet en una base de datos global.
Esto es especialmente útil para nuestro proyecto, ya que nos permite obtener información de
forma dinámica sobre cualquier dominio.


=== Wikidata

Wikidata es una base de conocimiento similar a Wikipedia, sin embargo, estructura su contenido
codificándolo como Linked Data.

Utiliza algunos elementos adicionales a los descritos en la sección anterior.
Estos son algunos ejemplos de dichos elementos que Wikidata utiliza para estructurar su contenido:

// IMAGEN
image:Datamodel_in_Wikidata.svg[]

Wikidata expone una API pública que utilizaremos para realizar consultas y obtener la
información de su grafo de conocimiento.
Para realizar dichas consultas utilizaremos en lenguaje SPARQL.