[[section-architecture]]
== Arquitectura

=== Estructura general

Este diagrama visual muestra una representación simplificada de la arquitectura del programa.

image:architecture.svg[alt=Program Architecture]

=== Edpoint Controllers

Responsables de gestionar las peticiones HTTP. Expone diferentes _endpoints_ descritos en la seccion _API Endpoints_.

Se comunica de forma directa tanto con el módulo _Search_ como con _Question Generator_ para que lleven
a cabo la funcionalidad necesaria.


=== Search Module

Se encarga de realizar la búsqueda de entidades a partir de una etiqueta representativa.
Esto es, recibe una _string_ y utiliza el módulo _Wikidata Local Service_ para obtener una lista de
entidades relacionadas.

=== Questions Generator Module

Este módulo contiene la funcionalidad principal de la aplicación. Se encarga del proceso descrito en la
sección _Questions Generation_.

Se comunica con el módulo _Categories_ para obtener la _plantilla_ elegida por el usuario.

Para recopilar toda la información necesaria para componer las preguntas, hace uso de la funcionalidad
implementada en el módulo _Wikidata Local Service_, que se conecta direntamente al grafo de conocimiento
de Wikidata.

=== Categories Module

Gestiona las diferentes _plantillas_ disponibles y se las proporciona al módulo  _Questions Generator_
para que genere las preguntas.

=== Wikidata Local Service Module

Es el responsable de gestionar la comunicación con la API de Wikidata.

Proporciona diferentes consultas y funciones a los módulos superiores para conseguir la información que
necesitan.

Este módulo está altamente acoplado a la implementación de la API de Wikidata. Cualquier cambio en la
especificación de dicha API podría significar tener que adaptar este módulo a dichos cambios.
