[[section-future-improvements]]
== Futuras mejoras

El modelo de _plantillas_ que utiliza el programa tiene algunas limitaciones.

Requiere que el usuario conozca las diferentes plantillas disponibles (potencialmente podría haber un
elevado número de ellas).

Además, tampoco es fácil de mantener por los propios desarrolladores. Nuevas propiedades, dominios o
soporte de nuevos idiomas podrían aparecer, lo que requeriría definir nuevos templates o redefinir los
existentes.

Sin embargo, abandonar la estrategia actual requeriría afrontar ciertos puntos.


=== Selección de propiedades

Algunas entidades no tienen un valor definido para ciertas propiedades.

El programa debería inferir el tipo de la entidad y, automáticamente elegir propiedades relevantes
para generar preguntas sobre dicha entidad basadas en el contexto.

=== Generación en lenguaje natural

El programa debería ser capaz de generar preguntas en lenguaje natural de forma automática a partir de
propiedades de Wikidata.


=== Dificultad progresiva

El sistema debería tener en cuenta el conocimiento del dominio por parte del usuario, para,
de esta manera, componer